### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by elgatito** [anacrolix/envpprof#3]
Hey,

Have just updated all the packages and now envprof can't compile:
```
# github.com/anacrolix/envpprof
../../go/src/github.com/anacrolix/envpprof/envpprof.go:28:3: undefined: "github.com/anacrolix/log".Printf
../../go/src/github.com/anacrolix/envpprof/envpprof.go:33:2: undefined: "github.com/anacrolix/log".Printf
../../go/src/github.com/anacrolix/envpprof/envpprof.go:53:3: undefined: "github.com/anacrolix/log".Print
../../go/src/github.com/anacrolix/envpprof/envpprof.go:56:2: undefined: "github.com/anacrolix/log".Printf
../../go/src/github.com/anacrolix/envpprof/envpprof.go:59:3: undefined: "github.com/anacrolix/log".Printf
../../go/src/github.com/anacrolix/envpprof/envpprof.go:79:4: undefined: "github.com/anacrolix/log".Printf
../../go/src/github.com/anacrolix/envpprof/envpprof.go:88:5: undefined: "github.com/anacrolix/log".Printf
../../go/src/github.com/anacrolix/envpprof/envpprof.go:93:5: undefined: "github.com/anacrolix/log".Printf
../../go/src/github.com/anacrolix/envpprof/envpprof.go:96:4: undefined: "github.com/anacrolix/log".Printf
../../go/src/github.com/anacrolix/envpprof/envpprof.go:104:4: undefined: "github.com/anacrolix/log".Printf
../../go/src/github.com/anacrolix/envpprof/envpprof.go:104:4: too many errors
```

**Comment by elgatito** [comment]
Can't understand, go.mod points to anacrolix/log v0.3.0, while in 0.3.0 `Print` is moved to a Logger. 
How could it work?

**Comment by elgatito** [comment]
I have reverted envprof to 0fc9d97023a3f2fdf60792660113013062b8a16d and it compiles fine now.

**Comment by elgatito** [comment]
@anacrolix should I make a PR with migrating Printf to logger.Printf?

**Comment by anacrolix** [comment]
Sorry, I didn't get a notification for this. I'll look into it shortly.

**Comment by anacrolix** [comment]
I can't reproduce this, but note that v0.3.0 is not on master. You should build using Go modules. If you're stuck on GOPATH, such as for gomobile support, you could use go mod vendor I think.

**Comment by anacrolix** [comment]
I've moved master to v0.3.0.

**Comment by elgatito** [comment]
Hm. It was a source code without usage of Go modules. 
It was using envpprof and `go get -u ./...` was done, that was throwing errors.

**Comment by elgatito** [comment]
I have updated all the packages and looks good so far. Thanks
